
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISPLAY = 2;
  public static final int LBRACKET = 42;
  public static final int EQUALS = 36;
  public static final int ARGSTRING = 23;
  public static final int DOUBLE = 48;
  public static final int INTEGER = 47;
  public static final int LPAREN = 37;
  public static final int PRIVATE = 7;
  public static final int INT = 14;
  public static final int FOR = 3;
  public static final int MINUS = 31;
  public static final int RCBRACKET = 41;
  public static final int RPAREN = 38;
  public static final int STATIC = 9;
  public static final int SEMICOLON = 39;
  public static final int NOT = 32;
  public static final int AND = 33;
  public static final int OR = 34;
  public static final int COMMA = 44;
  public static final int CLASS = 21;
  public static final int PLUS = 28;
  public static final int MAIN = 10;
  public static final int IF = 4;
  public static final int THIS = 20;
  public static final int DOT = 45;
  public static final int INTARRAY = 26;
  public static final int EOF = 0;
  public static final int BOOLEAN = 13;
  public static final int RETURN = 22;
  public static final int DOUBLELITERAL = 49;
  public static final int RBRACKET = 43;
  public static final int TRUE = 15;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int BECOMES = 29;
  public static final int VOID = 12;
  public static final int INTLITERAL = 25;
  public static final int TIMES = 30;
  public static final int ELSE = 5;
  public static final int LCBRACKET = 40;
  public static final int FINAL = 11;
  public static final int WHILE = 6;
  public static final int PUBLIC = 8;
  public static final int EXTENDS = 17;
  public static final int SYSTEMOUTPRINTLN = 24;
  public static final int FALSE = 16;
  public static final int LESS_THAN = 35;
  public static final int IMPLEMENTS = 19;
  public static final int LENGTH = 27;
  public static final int IDENTIFIER = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DISPLAY",
  "FOR",
  "IF",
  "ELSE",
  "WHILE",
  "PRIVATE",
  "PUBLIC",
  "STATIC",
  "MAIN",
  "FINAL",
  "VOID",
  "BOOLEAN",
  "INT",
  "TRUE",
  "FALSE",
  "EXTENDS",
  "NEW",
  "IMPLEMENTS",
  "THIS",
  "CLASS",
  "RETURN",
  "ARGSTRING",
  "SYSTEMOUTPRINTLN",
  "INTLITERAL",
  "INTARRAY",
  "LENGTH",
  "PLUS",
  "BECOMES",
  "TIMES",
  "MINUS",
  "NOT",
  "AND",
  "OR",
  "LESS_THAN",
  "EQUALS",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "LCBRACKET",
  "RCBRACKET",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "DOT",
  "IDENTIFIER",
  "INTEGER",
  "DOUBLE",
  "DOUBLELITERAL"
  };
}

